# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grandprix', '0002_auto_20171110_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('tournament_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grandprix.TournamentType')),
            ],
            options={
                'verbose_name_plural': 'Points',
            },
        ),
    ]
