# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandprix', '0004_player_tournament_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamenttype',
            name='pairing_type',
            field=models.PositiveIntegerField(choices=[(0, 'Auto'), (1, 'Manual'), (2, 'Round Robin'), (3, 'Swiss')], default=0),
        ),
    ]
