# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20171202_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='tourney_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.TournamentRound'),
        ),
        migrations.AlterField(
            model_name='game',
            name='black',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_black', to='player.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='white',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_white', to='player.Player'),
        ),
    ]
