# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20171202_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Points',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TournamentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pairing_type', models.PositiveIntegerField(choices=[(0, 'Auto'), (1, 'Manual'), (2, 'Round Robin'), (3, 'Swiss')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tournament',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='points',
            name='tournament_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.TournamentType'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.TournamentType'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Season'),
        ),
    ]
