# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
