# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_tournament_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentround',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='tag',
            field=models.PositiveIntegerField(),
        ),
    ]
