# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_auto_20171205_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentround',
            name='paired',
            field=models.BooleanField(default=False),
        ),
    ]
