# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_tournamentround_paired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='black',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_black', to='player.Player'),
        ),
    ]
