# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_tournament_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
