# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
